---
title: Movie Subtitles Analysis
author: Lookkid
date: "`r Sys.Date()`"
output: html_document
---

```{r echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(error=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(out.width="100%")

library(tidyverse)
library(jsonlite)
```

```{r}
printTable <- function(table, amount = 10) {
  print(str_glue('total ', length(row(table)), ' rows'))

  knitr::kable(head(table, n = amount))
}
```

# 1. Input data

## 1.1 Subtitles

```{r}
subtitles <- read_csv('data/labelled_data.csv') |>
  select(-text)
printTable(subtitles)
```

## 1.2 Movies

```{r}
readDirectorJson <- function(dir, nat, inf = '') {
  read_json(
    str_glue('data/', gsub(' ', '_', str_to_lower(dir), fixed = TRUE) , '_movies.json'),
    simplifyVector = TRUE,
    flatten = TRUE
    ) |>
  filter(SeriesEpisode == 0) |>
  mutate(
    id = as.numeric(MovieImdbID),
    name = MovieName,
    year = as.numeric(MovieYear),
    director = dir,
    nationality = nat,
    opensubtitlePath = `IDSubtitle.@MovieLink`,
    image = `MovieID.@MovieThumbURL`,
    info = inf,
    .keep = "none"
  )
}
```

```{r}
movies <- bind_rows(
  readDirectorJson("Apichatpong Weerasethakul", "🇹🇭",
    "Apichatpong works are well-known as non-straightforward, slow-paced, heavy picture-narrated films.
    Using only 27.1 average words per minute, the lowest number on the list."),
  readDirectorJson("Christopher Nolan", "🇬🇧🇺🇸",
    "Christopher Nolan, a father of complex Sci-fi movies, uses a lot of dialog to explain how theory in the film works.
    Dunkirk is the only outlier movie about wars that mainly uses cinematography as a narrative."),
  readDirectorJson("Hirokazu Koreeda", "🇯🇵",
    "Koreeda is a Japanese director who loves making drama films with conversation-driven storytelling.
    Dialog is used as a main medium to touch the audience's emotions."),
  readDirectorJson("Lee Chang-dong", "🇰🇷"),
  readDirectorJson("Rajkumar Hirani", "🇮🇳",
    "Rajkumar Hirani shows an interesting character that might represent an Indian movie:
    even though average words per minute are not the highest on the list, his films barely have a single minute without a dialog."),
  readDirectorJson("Wong Kar-wai", "🇭🇰")
) |>
  tibble()

printTable(movies |> select(-nationality, -info))
```

# 2. Wrangling

```{r}
parseMinute <- function(timestamp) {
  time <- strsplit(timestamp, ':', fixed=TRUE)
  hour <- map_chr(time, 1) |> as.numeric()
  minute <- map_chr(time, 2) |> as.numeric()

  return(hour * 60 + minute)
}
```

```{r}
data <- inner_join(
  movies |>
    select(id, name, director),
  subtitles |>
    mutate(minute = parseMinute(startAt)) |>
    select(id, minute, wordCount, label) |>
    group_by(id, minute, label) |>
    summarise(wordCount = sum(wordCount))
)

printTable(data)
```

# 3. Analysis

## 3.1 By director

```{r}
wordsByDirector <- data |>
  group_by(director, name) |>
  summarise(wordsPerMinute = sum(wordCount) / max(minute))

printTable(wordsByDirector, length(row(wordsByDirector)))
```

```{r}
ggplot(wordsByDirector, aes(x = director, y = wordsPerMinute, label = name)) +
  geom_point() +
  geom_text(hjust = 0, vjust = 0, size = 3) +
  ggtitle('Average movie words per minutes of each director')
```

## 3.2 By movie

```{r}
plotMoviesWordPerMinute <- function(dir) {
  data |>
    filter(director == dir) |>
    ggplot(aes(x = minute, y = wordCount, fill = label)) +
      geom_bar(stat='identity') +
      scale_fill_manual(values = c('#c04b4b', '#5d7fb2', '#34a134')) +
    facet_wrap(~name, ncol = 2) +
      ggtitle(str_glue('Words per minute by movie (', dir, ')'))
}
```

### 3.2.1 Apichatpong Weerasethakul

```{r}
plotMoviesWordPerMinute('Apichatpong Weerasethakul')
```

### 3.2.2 Christopher Nolan

```{r}
plotMoviesWordPerMinute('Christopher Nolan')
```

### 3.2.3 Hirokazu Koreeda

```{r}
plotMoviesWordPerMinute('Hirokazu Koreeda')
```

### 3.2.4 Rajkumar Hirani

```{r}
plotMoviesWordPerMinute('Rajkumar Hirani')
```

## 4. Write JSON output

### 4.1 directors.json

```{r}
directorOutput <- wordsByDirector |>
  right_join(movies) |>
  group_by(director, nationality, info) |>
  group_nest(.key = "movies") |>
  rename(name = director)

write_json(directorOutput, 'out/directors.json', pretty = TRUE)

directorOutput
```

### 4.2 word-frequency.csv

```{r}
wordFrequencyOutput <- data |>
  select(id, minute, label, wordCount) |>
  pivot_wider(names_from = 'label', values_from = wordCount, values_fill = 0) |>
  rename(movieId = id) |>
  write_csv('out/word-frequency.csv')

printTable(wordFrequencyOutput)
```
